/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-04-15 16:38:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<title>Trip Request</title>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900\" rel=\"stylesheet\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div class=\"wrapper d-flex align-items-stretch\">\n");
      out.write("		<nav id=\"sidebar\">\n");
      out.write("			<div class=\"custom-menu\">\n");
      out.write("				<button type=\"button\" id=\"sidebarCollapse\" class=\"btn btn-primary\">\n");
      out.write("					<i class=\"fa fa-bars\"></i>\n");
      out.write("				</button>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"p-4 pt-5\">\n");
      out.write("				<h1><a href=\"#\" class=\"logo\">Admin</a></h1>\n");
      out.write("				<ul class=\"list-unstyled components mb-5\">\n");
      out.write("\n");
      out.write("					<!-- <li class=\"active\">\n");
      out.write("						<a href=\"#homeSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" class=\"dropdown-toggle\"></a>\n");
      out.write("						<ul class=\"collapse list-unstyled\" id=\"homeSubmenu\">\n");
      out.write("							<li>\n");
      out.write("								<a href=\"#\">Home 3</a>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("					</li> -->\n");
      out.write("\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\">New Trip Request</a>\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\">Pending Requests</a>\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\">All Approved Requests</a>\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\">Find Employee</a>\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\">Logout</a>\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("				</ul>\n");
      out.write("\n");
      out.write("				<!-- <div class=\"mb-5\">\n");
      out.write("					<h3 class=\"h6\">For Test Purpose</h3>\n");
      out.write("				</div> -->\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</nav>\n");
      out.write("\n");
      out.write("		<!-- Page Content -->\n");
      out.write("\n");
      out.write("		<div id=\"content\" class=\"p-4 p-md-5 pt-5\">\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- All body contents will be displayed here -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Page Content end -->\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"js/popper.js\"></script>\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("	<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
